name: Typing and linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip -r requirements.txt
    - name: Run flake8
        run: flake8 .
    - name: Run mypy
        run: mypy .